//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ADRESSE
    {
        public short ID_ADR { get; set; }
        public int REF_IND_ADR { get; set; }
        public string LIB_ADR { get; set; }
        public string CP_ADR { get; set; }
        public Nullable<short> ID_LOC_ADR { get; set; }
        public Nullable<short> ID_DELEG_ADR { get; set; }
        public Nullable<short> ID_GOUV_ADR { get; set; }
        public Nullable<short> ID_NLDP { get; set; }
        public Nullable<bool> ACTIF_ADR { get; set; }
    
        public virtual T_INDIVIDU T_INDIVIDU { get; set; }
    }
}
