//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BCT_RCM00
    {
        public int ID_RCM00 { get; set; }
        public string Code_RCM00 { get; set; }
        public Nullable<decimal> C1_RCM00 { get; set; }
        public Nullable<decimal> C2_RCM00 { get; set; }
        public Nullable<decimal> C3_RCM00 { get; set; }
        public Nullable<decimal> C4_RCM00 { get; set; }
        public Nullable<decimal> C5_RCM00 { get; set; }
        public Nullable<decimal> C6_RCM00 { get; set; }
        public Nullable<decimal> C7_RCM00 { get; set; }
        public Nullable<decimal> C8_RCM00 { get; set; }
        public System.DateTime Date_RCM00 { get; set; }
        public Nullable<bool> Valide_RCM00 { get; set; }
    }
}
