//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BORD_FACTOR
    {
        public int ID_BORD_FACTOR { get; set; }
        public string NUM_BORD_FACTOR { get; set; }
        public Nullable<int> ID_FACTOR_BORD_FACTOR { get; set; }
        public int REF_CTR_BORD_FACTOR { get; set; }
        public Nullable<decimal> MONT_TOT_BORD_FACTOR { get; set; }
        public Nullable<System.DateTime> DAT_CRE_BORD_FACTOR { get; set; }
        public Nullable<System.DateTime> DAT_EDIT_BORD_FACTOR { get; set; }
        public bool VALID_BORD_FACTOR { get; set; }
        public Nullable<int> ID_ENC_BORD_FACTOR { get; set; }
        public string REF_ENC_BORD_FACTOR { get; set; }
    }
}
