//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Bordereau_MFG
    {
        public int ID_Bord_MFG { get; set; }
        public string Type_MFG { get; set; }
        public string Ref_ADH_MFG { get; set; }
        public string Ref_ACH_MFG { get; set; }
        public Nullable<int> Num_Bord_MFG { get; set; }
        public string Ref_Doc_MFG { get; set; }
        public Nullable<System.DateTime> Date_Bord_MFG { get; set; }
        public Nullable<decimal> MONT_TTC_DET_MFG { get; set; }
        public Nullable<int> Compte_MFG { get; set; }
        public Nullable<decimal> MONT_FDG_DET_MFG { get; set; }
        public Nullable<decimal> acc_fourn_adh_MFG { get; set; }
        public Nullable<decimal> Mnt_Finanancement_MFG { get; set; }
        public Nullable<System.DateTime> Date_Creation_MFG { get; set; }
        public Nullable<System.DateTime> Date_Envoie_MFG { get; set; }
        public Nullable<bool> Flag_MFG { get; set; }
    }
}
