//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BORD_MFG
    {
        public int ID_BORD_MFG { get; set; }
        public Nullable<int> REF_CTR_BORD_MFG { get; set; }
        public Nullable<int> REF_ADH_BORD_MFG { get; set; }
        public string NOM_ADH_BORD_MFG { get; set; }
        public string NUM_BORD_MFG { get; set; }
        public Nullable<decimal> MNT_COMM_HT_BORD_MFG { get; set; }
        public Nullable<System.DateTime> DATE_BORD_MFG { get; set; }
        public Nullable<System.DateTime> DATE_ENVOIE_BORD_MFG { get; set; }
    }
}
