//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CALC_INT
    {
        public int ID_CALC_INT { get; set; }
        public int REF_CTR_CALC_INT { get; set; }
        public Nullable<decimal> MONT_CALC_INT { get; set; }
        public Nullable<System.DateTime> DAT_CALC_INT { get; set; }
    
        public virtual T_CONTRAT T_CONTRAT { get; set; }
    }
}
