//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CALC_DISPO
    {
        public int ID_CALC_DISPO { get; set; }
        public Nullable<System.DateTime> DATE__CALC_DISPO { get; set; }
        public Nullable<decimal> DISPO_CALC_DISPO { get; set; }
        public Nullable<int> REF_ADH_CALC_DISPO { get; set; }
        public Nullable<int> REF_CTR_CALC_DISPO { get; set; }
        public Nullable<decimal> SOM_FACT_CALC_DISPO { get; set; }
        public Nullable<decimal> SOM_AVOIR_CALC_DISPO { get; set; }
        public Nullable<decimal> SOM_COMM_FACTOR_CALC_DISPO { get; set; }
        public Nullable<decimal> SOM_TVA_COMM_FATOR_CALC_DISPO { get; set; }
        public Nullable<decimal> SOM_DEBIT_CALC_DISPO { get; set; }
        public Nullable<decimal> SOM_CREDIT_CALC_DISPO { get; set; }
        public Nullable<decimal> SOM_FDG_FACT_CALC_DISPO { get; set; }
        public Nullable<decimal> SOM_FDG_LIBERE_CALC_DISPO { get; set; }
        public Nullable<decimal> FINANCE_CALC_DISPO { get; set; }
        public Nullable<decimal> INTERET_J_CALC_DISPO { get; set; }
        public Nullable<decimal> MARGE_J_CALC_DISPO { get; set; }
        public Nullable<decimal> TMM_J_CALC_DISPO { get; set; }
    }
}
