//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CALC_INT_IR
    {
        public int ID_CALC_IR { get; set; }
        public Nullable<int> REF_CTR_CALC_IR { get; set; }
        public string REF_DOCUMENT_DET_BORD_IR { get; set; }
        public Nullable<decimal> MONT_OUV_DET_BORD_IR { get; set; }
        public Nullable<System.DateTime> Date_Echeance_IR { get; set; }
        public Nullable<int> MAJOR_INT_INT_FIN_IR { get; set; }
        public Nullable<decimal> MONT_CALC_IR { get; set; }
    }
}
