//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CONTRAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_CONTRAT()
        {
            this.T_CALC_INT = new HashSet<T_CALC_INT>();
            this.T_DET_BORD = new HashSet<T_DET_BORD>();
            this.TJ_CIR = new HashSet<TJ_CIR>();
        }
    
        public int REF_CTR { get; set; }
        public string STATUT_CTR { get; set; }
        public string REF_CTR_PAPIER_CTR { get; set; }
        public Nullable<bool> SERVICE_CTR { get; set; }
        public string TYP_CTR { get; set; }
        public Nullable<System.DateTime> DAT_SIGN_CTR { get; set; }
        public Nullable<System.DateTime> DAT_DEB_CTR { get; set; }
        public Nullable<System.DateTime> DAT_RESIL_CTR { get; set; }
        public Nullable<System.DateTime> DAT_PROCH_VERS_CTR { get; set; }
        public Nullable<decimal> CA_CTR { get; set; }
        public Nullable<decimal> CA_EXP_CTR { get; set; }
        public Nullable<decimal> CA_IMP_CTR { get; set; }
        public Nullable<decimal> LIM_FIN_CTR { get; set; }
        public string DEVISE_CTR { get; set; }
        public Nullable<short> NB_ACH_PREVU_CTR { get; set; }
        public Nullable<short> NB_FACT_PREVU_CTR { get; set; }
        public Nullable<short> NB_AVOIRS_PREVU_CTR { get; set; }
        public Nullable<short> NB_REMISES_PREVU_CTR { get; set; }
        public Nullable<short> DELAI_MOYEN_REG_CTR { get; set; }
        public Nullable<short> DELAI_MAX_REG_CTR { get; set; }
        public Nullable<bool> FACT_REG_CTR { get; set; }
        public Nullable<decimal> DERN_MONT_DISP_2 { get; set; }
        public Nullable<decimal> MIN_COMM_FACT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CALC_INT> T_CALC_INT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_DET_BORD> T_DET_BORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TJ_CIR> TJ_CIR { get; set; }
    }
}
