//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CONTACT
    {
        public short ID_CONTACT { get; set; }
        public int REF_IND_CONTACT { get; set; }
        public string NOM_PRE_CONTACT { get; set; }
        public string POS_CONTACT { get; set; }
        public string TEL1_CONTACT { get; set; }
        public string TEL2_CONTACT { get; set; }
        public string MAIL1_COONTACT { get; set; }
        public string MAIL2_COONTACT { get; set; }
        public string FAX_CONTACT { get; set; }
        public Nullable<bool> ACTIF_CONTACT { get; set; }
    }
}
