//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Comm_MFG
    {
        public int Id_MFG { get; set; }
        public string Type_MFG { get; set; }
        public string Ref_ADH_MFG { get; set; }
        public string Code_MFG { get; set; }
        public Nullable<decimal> Mnt_Comm_MFG { get; set; }
        public Nullable<int> Num_Bord_MFG { get; set; }
        public Nullable<System.DateTime> date_Saisie_MFG { get; set; }
        public Nullable<System.DateTime> Date_Envoie_MFG { get; set; }
        public Nullable<bool> Flag_MFG { get; set; }
        public string Type_Action_MFG { get; set; }
    }
}
