//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CONFIGURATION_EMAIL
    {
        public Nullable<int> ID_FACTOR { get; set; }
        public string EMAIL { get; set; }
        public string MDP { get; set; }
        public string SMTP { get; set; }
        public Nullable<int> PORT { get; set; }
        public Nullable<bool> EnableSsl { get; set; }
        public int ID { get; set; }
    }
}
