//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DET_ASS
    {
        public int REF_ASS { get; set; }
        public Nullable<int> REF_CTR_ASS { get; set; }
        public Nullable<short> PRIME_ASS { get; set; }
        public Nullable<short> TX_COUVERTURE_ASS { get; set; }
        public Nullable<short> DELAIS_DECALARATION_SINISTRE_ASS { get; set; }
        public Nullable<short> ACTIF_ASS { get; set; }
    }
}
