//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DEM_FIN_CREDIT
    {
        public int ID_DEM_FIN_CREDIT { get; set; }
        public int ID_CIR_DEM { get; set; }
        public Nullable<decimal> MONT_FIN_DEM { get; set; }
        public Nullable<decimal> MONT_FIN_ACC { get; set; }
        public Nullable<System.DateTime> DAT_FIN_ACC { get; set; }
        public Nullable<decimal> MONT_CREDIT_DEM { get; set; }
        public Nullable<decimal> MONT_CREDIT_ACC { get; set; }
        public Nullable<System.DateTime> DAT_CREDIT_ACC { get; set; }
    }
}
