//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DOC_PHYSIQUE
    {
        public string TYP_DOC_PHY { get; set; }
        public int REF_CTR_DOC_PHY { get; set; }
        public Nullable<System.DateTime> DAT_VALID_DOC_PHY { get; set; }
        public Nullable<System.DateTime> DAT_EXPIR_DOC_PHY { get; set; }
        public Nullable<bool> DOC_BLOQ_DOC_PHY { get; set; }
        public string REF_USER_DOC_PHY { get; set; }
        public Nullable<bool> DOC_RECU_DOC_PHY { get; set; }
    }
}
