//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DOC_H_GED
    {
        public int id_H_GED { get; set; }
        public string LIBELLE_H_GED { get; set; }
        public System.DateTime DATE_TACHE_H_GED { get; set; }
        public Nullable<int> ID_GESTIONNAIRE_H_GED { get; set; }
        public string LIBELLE2_H_GED { get; set; }
        public Nullable<System.DateTime> DATE_ANN_H_GED { get; set; }
        public string MOTIF_ANN_H_GED { get; set; }
    }
}
