//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EC_COMPTABLE
    {
        public int ID_EC_CPT { get; set; }
        public string TYP_TR_EC_CPT { get; set; }
        public Nullable<System.DateTime> DAT_SAIS_EC_CPT { get; set; }
        public Nullable<System.DateTime> DAT_EFF_EC_CPT { get; set; }
        public Nullable<decimal> MONT_EC_CPT { get; set; }
        public string REF_EC_CPT { get; set; }
        public string DESC_EC_CPT { get; set; }
        public string ID_USER_EC_EPT { get; set; }
        public string LOT_EC_CPT { get; set; }
        public string DEVISE_EC_CPT { get; set; }
        public string CODE_ENT_EC_CPT { get; set; }
        public Nullable<long> LIGNE_EC_CPT { get; set; }
        public Nullable<int> REF_ADH_EC_CPT { get; set; }
        public string TYP_DOC_EC_CPT { get; set; }
        public string COD_JOURNAL_EC_CPT { get; set; }
        public string SEQ_COD_JOURNAL_EC_CPT { get; set; }
        public string DECS_SRC_CG_EC_CPT { get; set; }
        public string DOMAINE_EC_CPT { get; set; }
    }
}
