//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EMAIL
    {
        public int ID_EMAIL { get; set; }
        public int ID_USER { get; set; }
        public string TITRE_GROUPE { get; set; }
    }
}
