//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ETAT_DISPO
    {
        public int ID_ETAT_DISPO { get; set; }
        public Nullable<int> Ref_Ctr__ETAT_DISPO { get; set; }
        public Nullable<decimal> Total_Facture_ETAT_DISPO { get; set; }
        public Nullable<decimal> Total_Fin_ETAT_DISPO { get; set; }
        public Nullable<decimal> Total_Av_ETAT_DISPO { get; set; }
        public Nullable<decimal> Total_Comm_ETAT_DISPO { get; set; }
        public Nullable<decimal> Total_Frais_ETAT_DISPO { get; set; }
        public Nullable<decimal> Total_Debit_ETAT_DISPO { get; set; }
        public Nullable<decimal> Total_Credit_ETAT_DISPO { get; set; }
        public Nullable<decimal> Total_Interet_ETAT_DISPO { get; set; }
        public Nullable<decimal> Depass_Limite_ETAT_DISPO { get; set; }
        public Nullable<decimal> Total_Retenue_ETAT_DISPO { get; set; }
        public Nullable<decimal> Total_FDG_ETAT_DISPO { get; set; }
        public Nullable<decimal> Disponible_ETAT_DISPO { get; set; }
        public Nullable<System.DateTime> Date_ETAT_DISPO { get; set; }
        public Nullable<decimal> Total_Encours_Facture_ETAT_DISPO { get; set; }
        public Nullable<decimal> Total_IR_ETAT_DIPOS { get; set; }
        public Nullable<decimal> Total_Instru_Paiments_Imp_ETAT_DIPOS { get; set; }
        public Nullable<decimal> Total_Retard_Paiement_Algo_ETAT_DISPO { get; set; }
        public Nullable<decimal> Total_Litiges_ouvert_ETAT_DISPO { get; set; }
        public Nullable<decimal> Total_Disponible_2_ETAT_DISPO { get; set; }
        public Nullable<decimal> Total_Fonds_Reserve_ETAT_DISPO { get; set; }
        public Nullable<decimal> Total_Financement_du_mois_ETAT_DISPO { get; set; }
    }
}
