//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FRAIS_PAIEMENT
    {
        public string TYP_FRAIS_PAIE { get; set; }
        public int REF_CTR_FRAIS_PAIE { get; set; }
        public Nullable<decimal> MONT_PAR_INSTR_FRAIS_PAIE { get; set; }
        public string LIB_FRAIS_PAIE { get; set; }
    }
}
