//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GROUPE
    {
        public int ID_GROUP { get; set; }
        public Nullable<int> REF_IND_GROUP { get; set; }
        public string NOM_GROUP { get; set; }
    }
}
