//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HISTORIQUE
    {
        public int ID_HISTORIQUE { get; set; }
        public Nullable<System.DateTime> DATE_ACTION { get; set; }
        public string ACTION { get; set; }
        public string T_TABLE { get; set; }
        public string ID_ENREGISTREMENT { get; set; }
        public string LOGIN_USER { get; set; }
        public string IP_PC { get; set; }
        public string NOM_PC { get; set; }
        public string REF_CTR_HIST { get; set; }
        public string REF_IND_HIST { get; set; }
        public string ABREV_ROLE_HIST { get; set; }
        public int ID_HISTORIQUEE { get; set; }
    }
}
