//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_IMPAYE
    {
        public int ID_IMP { get; set; }
        public int ID_ENC_IMP { get; set; }
        public Nullable<int> ID_DET_BORD_IMP { get; set; }
        public Nullable<System.DateTime> DATE_IMP { get; set; }
        public Nullable<System.DateTime> DATE_SAISI_IMP { get; set; }
        public Nullable<decimal> MONT_IMP { get; set; }
        public Nullable<System.DateTime> DATE_RESOL_IMP { get; set; }
        public string ID_NV_ENCS { get; set; }
        public Nullable<bool> IS_RESOLU { get; set; }
    }
}
