//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INFO_CTR
    {
        public int ID_INFO_CTR { get; set; }
        public Nullable<int> REF_INFO_CTR { get; set; }
        public string LIBELLE_INFO_CTR { get; set; }
        public Nullable<System.DateTime> DATE_INFO_CTR { get; set; }
        public Nullable<int> ID_USER_INFO_CTR { get; set; }
    }
}
