//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INT_FINANCEMENT
    {
        public string TYP_INSTR_INT_FIN { get; set; }
        public int REF_CTR_INT_FIN { get; set; }
        public Nullable<decimal> TX_INT_MARCHE_INT_FIN { get; set; }
        public Nullable<decimal> TX_MARGE_CTR_INT_FIN { get; set; }
        public Nullable<short> DELAI_MAX_PAI_INT_FIN { get; set; }
        public Nullable<decimal> PRECOMPTE_INT_FIN { get; set; }
        public Nullable<decimal> MAJOR_INT_INT_FIN { get; set; }
        public Nullable<System.DateTime> DAT_DEB_VALID_INT_FIN { get; set; }
    }
}
