//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LITIGE
    {
        public string TYP_LIT { get; set; }
        public int REF_CTR_LIT { get; set; }
        public Nullable<System.DateTime> DAT_LIT { get; set; }
        public Nullable<System.DateTime> ECH_LIT { get; set; }
        public Nullable<decimal> MONT_LT { get; set; }
        public Nullable<bool> ETAT_LIT { get; set; }
        public Nullable<short> ID_DET_BORD_LIT { get; set; }
        public int ID_LITIGE { get; set; }
    }
}
