//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MOTIF_PROG
    {
        public int REF_CTR_MOTIF_PROG { get; set; }
        public string TYP_MOTIF_PROG { get; set; }
        public string LIB_MOTIF_PROG { get; set; }
        public Nullable<bool> ALERTE_LIT_MOTIF_PROG { get; set; }
        public Nullable<System.DateTime> DAT_MOTIF_PROG { get; set; }
        public Nullable<System.DateTime> ECH_MOTIF_PROG { get; set; }
        public Nullable<bool> FRAIS_MOTIF_PROG { get; set; }
        public string LOGIN_USER_MOTIF_PROG { get; set; }
    }
}
