//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MVT_CREDIT
    {
        public int ID_CREDIT { get; set; }
        public int REF_CTR_CREDIT { get; set; }
        public string ABRV_CREDIT { get; set; }
        public string TYP_CREDIT { get; set; }
        public Nullable<decimal> MONT_CREDIT { get; set; }
        public Nullable<System.DateTime> DATE_CREDIT { get; set; }
        public string LIBELLE_LIBRE_CREDIT { get; set; }
        public string REF_ENC_CREDIT { get; set; }
        public Nullable<System.DateTime> DAT_VAL_ENC_CREDIT { get; set; }
    }
}
