//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MVT_DEBIT
    {
        public int ID_DEBIT { get; set; }
        public int REF_CTR_DEBIT { get; set; }
        public string ABEV_DEBIT { get; set; }
        public string TYP_DEBIT { get; set; }
        public Nullable<decimal> MONT_DEBIT { get; set; }
        public Nullable<System.DateTime> DATE_DEBIT { get; set; }
    }
}
