//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PROROGATION
    {
        public int REF_CTR_PROG { get; set; }
        public string TYP_PROG { get; set; }
        public string MOTIF_PROG { get; set; }
        public Nullable<System.DateTime> DAT_PROG { get; set; }
        public System.DateTime ECH_PROG { get; set; }
        public Nullable<bool> ETAT_PROG { get; set; }
        public int ID_DET_BORD_PROG { get; set; }
        public int ID_PROROGATION { get; set; }
    }
}
