//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RELANCE
    {
        public int ID_RELANCE { get; set; }
        public string REF_CTR_RELANCE { get; set; }
        public string LIBELLE_RELANCE { get; set; }
        public Nullable<System.DateTime> DATE_RELANCE { get; set; }
        public string REF_DOC_RELANCE { get; set; }
        public Nullable<bool> VALIDE_RELANCE { get; set; }
        public string USER_RELANCE { get; set; }
    }
}
