//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_UN
    {
        public string ID_TABLE_UN { get; set; }
        public Nullable<int> REF_ADH_TBLE_UN { get; set; }
        public string COMPTE_TABLE_UN { get; set; }
        public string CODE_TABLE_UN { get; set; }
        public string LIBELLEE_TABLE_UN { get; set; }
        public string INTITULE_TABLE_UN { get; set; }
        public Nullable<decimal> DEBIT_TABLE_UN { get; set; }
        public Nullable<decimal> CREDIT_TABLE_UN { get; set; }
        public Nullable<System.DateTime> DATE_TABLE_UN { get; set; }
        public string REF_MFG_ADH_TABLE_UN { get; set; }
        public string COLONNE_DEUX_TABLE_UN { get; set; }
        public string COLONNE_TROIS_TABLE_UN { get; set; }
        public string COLONNE_QUATRE_TABLE_UN { get; set; }
    }
}
