//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJ_ACH_EX
    {
        public int ID_ACH_EX { get; set; }
        public int REF_CTR_ACH_EX { get; set; }
        public int REF_IND_ACH_EX { get; set; }
        public string ID_ROLE_CIR { get; set; }
    }
}
