//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJ_ADH_WEB
    {
        public int ID_WEB { get; set; }
        public int REF_IND_WEB { get; set; }
        public string PRE_IND_WEB { get; set; }
        public string LOGIN_WEB { get; set; }
        public string PWD_WEB { get; set; }
        public System.DateTime DATE_DEBUT_WEB { get; set; }
        public Nullable<System.DateTime> DATE_FIN_WEB { get; set; }
    }
}
