//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJ_CIR
    {
        public int ID_CIR { get; set; }
        public int REF_CTR_CIR { get; set; }
        public int REF_IND_CIR { get; set; }
        public string ID_ROLE_CIR { get; set; }
    
        public virtual T_CONTRAT T_CONTRAT { get; set; }
        public virtual T_INDIVIDU T_INDIVIDU { get; set; }
        public virtual T_ROLE T_ROLE { get; set; }
    }
}
