//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJ_DOCUMENT_DET_BORD
    {
        public int ID_DOCUMENT_DET_BORD { get; set; }
        public string ID_DET_BORD { get; set; }
        public string NUM_BORD { get; set; }
        public int REF_CTR_DET_BORD { get; set; }
        public string REF_DOCUMENT_DET_BORD { get; set; }
    
        public virtual TJ_DOCUMENT_DET_BORD TJ_DOCUMENT_DET_BORD1 { get; set; }
        public virtual TJ_DOCUMENT_DET_BORD TJ_DOCUMENT_DET_BORD2 { get; set; }
    }
}
