//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_ACTPROF_BCT
    {
        public string Code_Section { get; set; }
        public string Section { get; set; }
        public string Code_SousSection { get; set; }
        public string SousSection { get; set; }
        public string Code_Activité { get; set; }
        public string Code_Classe { get; set; }
        public string Classe { get; set; }
        public string Code_Classe1 { get; set; }
        public string Code_SousClasse { get; set; }
        public string SousClasse { get; set; }
    }
}
