//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_Ag_Bq
    {
        public string Code_Bq_Ag { get; set; }
        public string Code_Bq { get; set; }
        public string Banque { get; set; }
        public string Code_Ag { get; set; }
        public string Agence { get; set; }
    }
}
