//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_COMM_FACTORING
    {
        public string TYP_COMM_FACTORING { get; set; }
        public string TX_COMM_FACTORING { get; set; }
        public Nullable<decimal> MONT_MIN_DOC_COMM_FACTORING { get; set; }
        public Nullable<decimal> MONT_MIN_CTR_COMM_FACTORING { get; set; }
        public int ID_COMM_FACT { get; set; }
    }
}
