//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_CP
    {
        public string CP { get; set; }
        public string Ville { get; set; }
        public string Code_Gouvernorat { get; set; }
        public string Gouvernorat { get; set; }
        public string Code_Region { get; set; }
        public string Region { get; set; }
        public int ID_CP { get; set; }
    }
}
