//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_LISTE_FRAIS_DIVERS
    {
        public string ABREV_FRAIS_DIVERS { get; set; }
        public string LIB_FRAIS_DIVERS { get; set; }
        public Nullable<decimal> MONT_FRAIS_DIVERS { get; set; }
        public string TYPE_FRAIS_DIVERS { get; set; }
        public int ID_ListeFraisDivers { get; set; }
    }
}
