//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_LIST_VAL
    {
        public string ABR_LIST_VAL { get; set; }
        public string TYP_LIST_VAL { get; set; }
        public Nullable<short> ORD_LIST_VAL { get; set; }
        public string LIB_LIST_VAL { get; set; }
        public string COM_LIST_VAL { get; set; }
        public int ID_LIST_VAL { get; set; }
    }
}
