//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_NLDP
    {
        public int ID_NLDP { get; set; }
        public string LIB_NT { get; set; }
        public string ABRV_NAT { get; set; }
        public string LIB_LANG { get; set; }
        public string ABRV_LANG { get; set; }
        public string LIB_DEVISE { get; set; }
        public string ABRV_DEVISE { get; set; }
        public string LIB_PAYS { get; set; }
        public string ABRV_PAYS { get; set; }
    }
}
