//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_PARAM_PIECE
    {
        public string TYP_PARAM_PIECE { get; set; }
        public string LIB_PARAM_PIECE { get; set; }
        public string SIGN_PARAM_PIECE { get; set; }
    }
}
