//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_RIB
    {
        public string RIB_RIB { get; set; }
        public int REF_IND_RIB { get; set; }
        public bool ACTIF_RIB { get; set; }
    }
}
