//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_TMM
    {
        public Nullable<System.DateTime> DATE_DEBUT_TMM { get; set; }
        public Nullable<System.DateTime> DATE_FIN_TMM { get; set; }
        public Nullable<decimal> TAUX_TMM { get; set; }
        public int ID_TMM { get; set; }
    }
}
