//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_TVA
    {
        public short ID_TVA { get; set; }
        public string LIB_TVA { get; set; }
        public Nullable<decimal> VAL_TVA { get; set; }
    }
}
