//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xfactor.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class TS_USER
    {
        public short ID_USER { get; set; }
        public short ID_GRP_USER { get; set; }
        public string NOM_USER { get; set; }
        public string PRE_USER { get; set; }
        public string LOGIN_USER { get; set; }
        public string MDP_USER { get; set; }
        public bool ACTIF_USER { get; set; }
        public string FONCTION_USER { get; set; }
        public string SERVICE_USER { get; set; }
        public string DIRECTION_USER { get; set; }
        public string AGENCE_USER { get; set; }
        public string MAIL_USER { get; set; }
        public string TEL_FIXE_USER { get; set; }
        public string MOBILE_USER { get; set; }
        public string PHOTO_USER { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public string ONE_SIGNAL_PLAYER_ID { get; set; }
        public virtual TS_GRP_USER TS_GRP_USER { get; set; }
    }
}
